apiVersion: v1
kind: Service
metadata:
  name: my-web-app-service
spec:
  type: LoadBalancer
  selector:
    app: my-web # This must match the Pod labels
  ports:
  - protocol: TCP
    port: 9001
    targetPort: 80